### ISSUE TITLE
Allow robots.txt

### ISSUE THREAD

**Issue by oneelement** [jwpf100/essential-coaching-app#40]
https://github.com/jwpf100/essential-coaching-app/blob/502bf4503dbf9d12152b3253df6381a876aaae8a/public/robots.txt#L1

You done this on purpose, site won't get indexed with this?

**Comment by jwpf100** [comment]
@oneelement 
That allows access to all robots from what I read.  If I put a / afterwards it would block them all: 
`User-agent: * Disallow: / `
